//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koala.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.Línea_Pedido = new HashSet<Línea_Pedido>();
        }
    
        public int Id_Pedido { get; set; }
        public int Cliente { get; set; }
        public System.DateTime Fecha_Pedido { get; set; }
        public Nullable<System.DateTime> Confirmado { get; set; }
        public Nullable<System.DateTime> Cobrado { get; set; }
        public Nullable<System.DateTime> Enviado { get; set; }
        public Nullable<System.DateTime> Recibido { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Línea_Pedido> Línea_Pedido { get; set; }
    }
}
